### ISSUE TITLE
Render parcel boundaries and labels

### ISSUE THREAD

**Issue by rkelson** [agrc/Parcels#10]
Parcels boundaries should render at Level 11
Parcel labels should render at level 13

Once this is set up we will look further into tuning what levels things should render at

**Comment by steveoh** [comment]
Just a reminder, the levels are different in the appliance caches. Did you take that into account?

**Comment by rkelson** [comment]
understood
I was using the levels associated with
http://mapserv.utah.gov/rasterindices/Parcels.html

I'm sure we might tune it once we see this in test

Rick Kelson
Utah AGRC
801.538.3237
gis.utah.gov
