### ISSUE TITLE
search autocomplete and partial search not working

### ISSUE THREAD

**Issue by BGranberg** [agrc/Parcels#15]
I don't get a partial matches or autocomplete in the search after selecting a county. Chrome on mac. Exact match works though.

![screen shot 2016-01-12 at 10 22 48 pm](https://cloud.githubusercontent.com/assets/1766038/12285790/0a982a58-b97b-11e5-9282-384b49ff1083.png)

**Comment by steveoh** [comment]
We removed autocomplete #12
