### ISSUE TITLE
Lite basemap parcel lines not lining up with parcel boundaries

### ISSUE THREAD

**Issue by rkelson** [agrc/Parcels#19]
The parcel boundaries depicted in the Lite basemap do not line up perfectly with the actual parcel feature service. Why?
The larges offset I've found is in the Vernal area.

**Comment by steveoh** [comment]
Good question. I wonder if @stdavis or @ZachBeck did something goofy with the mxd's when making that cache.

**Comment by steveoh** [comment]
![image](https://cloud.githubusercontent.com/assets/325813/12311796/ebec844a-ba16-11e5-913a-9fd20ff8dcec.png)

They sure do look funny.

**Comment by stdavis** [comment]
I wonder if it's a transformation method issue. @steveoh What transformation method did you use when reprojecting the data for this service?

**Comment by steveoh** [comment]
I used 

```
Name: GCS_WGS_1984
Angular Unit: Degree (0.0174532925199433)
Prime Meridian: Greenwich (0.0)
Datum: D_WGS_1984
  Spheroid: WGS_1984
    Semimajor Axis: 6378137.0
    Semiminor Axis: 6356752.314245179
    Inverse Flattening: 298.257223563
```

I am unsure as to what transformation method was used since arcpy probably chose that for me. What transformation should I explicitly be using?

**Comment by stdavis** [comment]
I haven't ever passed a geographic transformation either. The docs say that it chooses the default one which I'm not sure is correct for Utah. I'm going to ask Sean which one we should be using. Then if we can standardize on one I'm thinking that this issue will go away.

**Comment by steveoh** [comment]
It was a geographic transformation issue and forklift has solved this issue. Things should be lined up now.
