### ISSUE TITLE
Add ACCOUNT_NUMBER to identify results in parcels.utah.gov

### ISSUE THREAD

**Issue by rkelson** [agrc/parcels#202]
Parcels can have numerous unique identifying values. The most common are the values we populate the PARCEL_ID field with. Some counties have requested we also maintain account_number values in their parcels and we have done so for years.

The field ACCOUNT_NUMBER has recently been added to all Basic county parcels in Internal and will be maintained in counties where possible. In addition to added information for our uses, it also facilitates a crosswalk between the GIS and Assessor office tax roll information.

I would suggest adding it to the identify results after Generalized Ownership Type labeled as _Alternate ID_ or _Alternate Parcel Number_

**Comment by nathankota** [comment]
> The field ACCOUNT_NUMBER has recently been added to all Basic county parcels in Internal...

Is the first step to alter Forklift to get the new attribute in the county parcel feature services (e.g. [Utah](https://services1.arcgis.com/99lidPhWCzftIe9K/ArcGIS/rest/services/Parcels_Utah/FeatureServer/0)) and [StateWideParcels](https://services1.arcgis.com/99lidPhWCzftIe9K/arcgis/rest/services/UtahStatewideParcels/FeatureServer/0/)?

**Comment by steveoh** [comment]
Is there something specific with Utah county parcels that needs to happen?

**Comment by nathankota** [comment]
> Is there something specific with Utah county parcels that needs to happen? 
Not sure - I was using it as an example to show that the new attribute wasn't yet in the basic county parcel layers (if that is the intention), nor the statewide layer.

**Comment by rkelson** [comment]
I am just noticing what Nathan is saying. The field exists in all Internal Basic parcel layers but the counties, such as Utah County that it was added to recently, do not reflect this additional attribute in OpenData

**Comment by steveoh** [comment]
I believe there needs to be some coordination between the data and dev team when new fields are added. It appears that has started https://github.com/agrc/warehouse/pull/149. Since the data doesn't reflect that change, I will reset the hashing data for the parcels. Then on Friday or early next week we can see if the new data has propagated.

**Comment by steveoh** [comment]
This was released october 3, 49594c998e57fe055a76f2d5ddfea9dcf3a0e723
