### ISSUE TITLE
County Name as a URL Parameter

### ISSUE THREAD

**Issue by brigsz** [agrc/Parcels#25]
Grand County is ready to upgrade their site for us.  If we could pass them a URL such as mapserv.utah.gov/parcels?county=GRAND. Then the app would load with Grand County in the title and zoomed to the extent of the county. 

The current link is http://www.grandcountyutah.net/790/Parcel-Viewer-Map  and as you would suspect it is busted.

**Comment by herrchin** [comment]
Counties with a space in their full name don't appear to work with the space encoded as %20 or a + sign, so you can't create a valid URL link to them.

**Comment by steveoh** [comment]
[Salt Lake](http://mapserv.utah.gov/#/Salt Lake) should work now ✅
