### ISSUE TITLE
Broken Build

### ISSUE THREAD

**Issue by steveoh** [agrc/Parcels#39]
> bower ECONFLICT     Unable to find suitable version for dstore
> The command "bower install" failed and exited with 1 during .

**Comment by stdavis** [comment]
I'm not seeing this anymore. Feel free to reopen if this is still an issue.

**Comment by stdavis** [comment]
Actually didn't realize that you were talking about the Travis build...

**Comment by steveoh** [comment]
I think we need a dstore resolution for bower.
