### ISSUE TITLE
"Overlay" for house numbers obscured by parcel IDs

### ISSUE THREAD

**Issue by herrchin** [agrc/Parcels#43]
Feature request: Please have the house number "overlay" layer foreground with respect to the parcel IDs. Thanks!

**Comment by steveoh** [comment]
will you supply a screenshot

**Comment by herrchin** [comment]
Sure!

![image](https://cloud.githubusercontent.com/assets/2927705/21163922/7303062e-c15b-11e6-86c8-49e874371914.png)

**Comment by steveoh** [comment]
Sorry to do this but I'm going to have to close this as `wontfix`. The `Overlay` is a generic layer that is used in multiple applications and if we tweak this in one place then it won't align in others. The parcels shapes aren't regular and the parcel id numbers are long so I don't think there is a perfect solution for label placements.

Being the parcel app, we feel as though the parcel # is more important than the house number. And you can get all of the parcel information with a click on the map.

Once again, I apologize for the label collisions.
