### ISSUE TITLE
Wasatch County New URL

### ISSUE THREAD

**Issue by brigsz** [agrc/Parcels#46]
The link on the identify results to a parcel map for Wasatch County is outdated.  It should be

 http://wasatch.maps.arcgis.com/apps/webappviewer/index.html?id=fe65f93c14a84f44814a81f97fa0fa5b
![wasatch](https://user-images.githubusercontent.com/6306463/30332651-10cfde82-9798-11e7-84a3-f2d609b56bf3.png)

The "The county parcel website" button is the one that has an old link

**Comment by steveoh** [comment]
That link is stored in the data. I think @rkelson would need to recalculate that field.

**Comment by rkelson** [comment]
I updated the link in my code, on the webpage, SDE, Drive and FTP. The next forklift should fix the URL in the app
