### ISSUE TITLE
pallet build issue

### ISSUE THREAD

**Issue by steveoh** [agrc/Parcels#47]
if the hash directory hasn't been created yet the pallet fails to build.

create the directory if it doesn't exist.

https://github.com/agrc/Parcels/blob/master/scripts/ParcelPallet.py#L90

refs https://github.com/agrc/forklift/issues/249

**Comment by stdavis** [comment]
Shouldn't creating the hash directory be a forklift concern?

**Comment by steveoh** [comment]
Yeah probably.
