### ISSUE TITLE
Add county to parcel info panel

### ISSUE THREAD

**Issue by nathankota** [agrc/parcels#69]
> Hi there, it would exceptionally helpful if this screen could also show the source county in the results show after searching by street address.  Ultimately the parcel # is used to locate a project on the SCR.  The SCR search requires you provide the county along with the parcel # in order to search the SCR by parcel #.  I would save having to click the County Parcel Website button to determine the parcel county.
> 
> Thank you,
> Donna Dorado

![image](https://user-images.githubusercontent.com/15659642/143276290-41a5d4ca-36c4-49ee-a654-c14a26be5f1c.png)

**Comment by eneemann** [comment]
That was fast!
