### ISSUE TITLE
Broken on Safari

### ISSUE THREAD

**Issue by rkelson** [agrc/parcels#74]
Received an email from a concerned user. Sounds like while connected to WiFi the app works on most mobile platforms but not mobile Apple platforms. Can anything be done to open the door for mobile Apple users to the app?

**Comment by nathankota** [comment]
a little more info from the user:

> ...it appears to not be working only on Apple devices (IPhones and iPads)...We are trying to access it on both Safari and Chrome  applications. 

![image](https://user-images.githubusercontent.com/15659642/146274918-38bc2e23-eb2e-4ef3-ae0e-9a70ca580968.png)

**Comment by stdavis** [comment]
Reproduced on my iPhone XR via Chrome.

**Comment by stdavis** [comment]
Reproduced on Safari desktop as well. I'll take a look at this today or tomorrow morning...

**Comment by stdavis** [comment]
It seems that the issue is that [this regex](https://github.com/agrc/parcels/blob/ac4736ac7390d9edcc1b16f5eeb1c4e7d18b6c59/src/PageElements.jsx#L353) is using a negative look behind which is not supported on Safari.

**Comment by stdavis** [comment]
@rkelson This fix has been pushed to production. Would you mind verifying with the user that it is fixed for them?

**Comment by rkelson** [comment]
It works!

"Yes we just tried it and it worked great! And yes, it has been working for
years on the iPads, until recently! Thanks again, all of our appraisers are
very grateful at this time!"

Rick Kelson
Utah Geospatial Resource Center (UGRC)
*Yes we've changed our name
<https://gis.utah.gov/agrc-name-change-to-utah-geospatial-resource-center-ugrc/>*
801.433.7891
gis.utah.gov
