### ISSUE TITLE
Parcel search not working

### ISSUE THREAD

**Issue by rkelson** [agrc/Parcels#8]
If i copy and paste a parcel ID (SLCo# 16261050280000) the parcel is not found although the auto complete pops up below the value I pasted.

The results seem to have the trailing zeros 'padding' removed and may be the cause the problem.
![image](https://cloud.githubusercontent.com/assets/6200941/12240206/8130ad9e-b849-11e5-9d69-b535130c7e6a.png)

**Comment by steveoh** [comment]
fixed in version 0.2.0
